name: Build docker image to ensure all steps exist in the cache

on:
  workflow_call:
    inputs:
      image-target:
        type: string
    outputs:
      image-name:
        description: 'The name of the created image'
        value: ${{ jobs.build-docker-image.outputs.image-name }}
      app-version:
        value: ${{ jobs.build-docker-image.outputs.app-version }}

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.build-docker-image.outputs.app-version }}
      app-version: ${{ steps.get-app-version.outputs.app-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get app version
        id: get-app-version
        uses: infoxchange/github-ci/actions/get-app-version@main

      - name: Build docker image
        id: build-docker-image
        uses: infoxchange/github-ci/actions/setup-docker-image@main
        with:
          load-image: false
          target: ${{ inputs.image-target }}
          build-args: |
            APP_VERSION=${{ steps.get-app-version.outputs.app-version }}
